/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogExceptionPanel.java
 *
 * Created on 01/11/2010, 10:51:02
 */

package com.jpower.utils;

import java.awt.Component;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import javax.swing.JOptionPane;

/**
 *
 * @author F6036477
 */
public class DialogExceptionPanel1 extends javax.swing.JPanel {

  private String prefix;

  private Throwable error;
  
  private Component component;


  /** Creates new form DialogExceptionPanel */
  public DialogExceptionPanel1() {
    prefix = "Ocorreu um erro de execução:";
    error = null;
    component = null;
    initComponents();
  }


  public Throwable getError()
  {
    return error;
  }


  public void setError(Throwable error)
  {
    this.error = error;
  }


  public Component getComponent()
  {
    return component;
  }


  public void setComponent(Component component)
  {
    this.component = component;
  }


  public String getPrefix()
  {
    return prefix;
  }


  public void setPrefix(String prefix)
  {
    this.prefix = prefix;
  }


  public void showDialog()
  {
    if(error == null) return;

    prefixLabel.setText("<html><h4>" + prefix
        + "</h4><br>" + error.getMessage()
        + "</html");

    ByteArrayOutputStream bos = new ByteArrayOutputStream();
    PrintStream ps = new PrintStream(bos, true);
    error.printStackTrace(ps);

    //errorArea.setText(new String(bos.toByteArray()));

    JOptionPane.showMessageDialog(component, this, "ERROR", JOptionPane.ERROR_MESSAGE);
  }


  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    prefixLabel = new javax.swing.JLabel();
    scroll = new javax.swing.JScrollPane();
    errorArea = new javax.swing.JTextArea();

    setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    prefixLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    prefixLabel.setText("<html><h4>Ocorreu um erro de execução:</h4><br>");
    add(prefixLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 60));

    errorArea.setColumns(20);
    errorArea.setEditable(false);
    errorArea.setLineWrap(true);
    errorArea.setRows(5);
    scroll.setViewportView(errorArea);

    add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 360, 120));
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea errorArea;
  private javax.swing.JLabel prefixLabel;
  private javax.swing.JScrollPane scroll;
  // End of variables declaration//GEN-END:variables

}
