/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package us.pserver.coder;


/**
 *
 * @author juno
 */
public class FormAttribute extends javax.swing.JPanel {

  private Object value;
  
  /**
   * Creates new form FormColor
   */
  public FormAttribute() {
    initComponents();
    value = null;
  }
  
  
  public Object getValue() {
    return value;
  }
  
  
  public void setValue(Object val) {
    value = val;
  }
  
  
  public <T> T castValue() {
    if(value == null) return null;
    try {
      return (T) value;
    } catch(ClassCastException c) {
      return null;
    }
  }
  
  
  public boolean isValueTypeOf(Class c) {
    if(value == null) return false;
    return c.isAssignableFrom(value.getClass());
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    label = new javax.swing.JLabel();
    button = new javax.swing.JButton();

    setBackground(new java.awt.Color(255, 255, 255));
    setPreferredSize(new java.awt.Dimension(250, 30));
    setLayout(new java.awt.BorderLayout());
    add(label, java.awt.BorderLayout.CENTER);

    button.setPreferredSize(new java.awt.Dimension(115, 28));
    add(button, java.awt.BorderLayout.EAST);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton button;
  public javax.swing.JLabel label;
  // End of variables declaration//GEN-END:variables
}
