/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package us.pserver.coder;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;


/**
 *
 * @author juno
 */
public class FrameEditor extends javax.swing.JFrame {

  private Editor editor;
  
  private int buttonBarHeight;
  
  /**
   * Creates new form FrameEditor
   */
  public FrameEditor() {
    editor = new Editor();
    LineNumberPanel lnp = new LineNumberPanel(editor);
    initComponents();
    buttonBarHeight = buttonBar.getPreferredSize().height;
    scroll.setViewportView(lnp);
    scroll.repaint();
    editor.addKeyListener(new KeyAdapter() {
      public void keyReleased(KeyEvent e) {
        if(e.getKeyCode() == KeyEvent.VK_H && e.isControlDown()) {
          toggleButtonBar();
        }
      }
    });
  }
  
  
  public void toggleButtonBar() {
    Dimension d = buttonBar.getPreferredSize();
    if(d.height == 1)
      d.height = buttonBarHeight;
    else
      d.height = 1;
    buttonBar.setSize(d);
    buttonBar.setPreferredSize(d);
    buttonBar.repaint();
    content.revalidate();
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    content = new javax.swing.JPanel();
    buttonBar = new javax.swing.JPanel();
    actionLabel1 = new us.pserver.coder.ActionLabel();
    actionLabel2 = new us.pserver.coder.ActionLabel();
    actionLabel3 = new us.pserver.coder.ActionLabel();
    actionLabel4 = new us.pserver.coder.ActionLabel();
    actionLabel5 = new us.pserver.coder.ActionLabel();
    replButton = new us.pserver.coder.ActionLabel();
    actionLabel7 = new us.pserver.coder.ActionLabel();
    actionLabel8 = new us.pserver.coder.ActionLabel();
    actionLabel9 = new us.pserver.coder.ActionLabel();
    actionLabel10 = new us.pserver.coder.ActionLabel();
    scroll = new javax.swing.JScrollPane();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    content.setLayout(new java.awt.BorderLayout());

    buttonBar.setBackground(new java.awt.Color(80, 80, 80));

    actionLabel1.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/circle-save-24.png"))); // NOI18N
    actionLabel1.setText("Save");

    actionLabel2.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/circle-open-24.png"))); // NOI18N
    actionLabel2.setText("Open");

    actionLabel3.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/copy-plus-24.png"))); // NOI18N
    actionLabel3.setText("Copy");

    actionLabel4.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/paste-24.png"))); // NOI18N
    actionLabel4.setText("Paste");

    actionLabel5.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/search-24.png"))); // NOI18N
    actionLabel5.setText("Find");

    replButton.setForeground(new java.awt.Color(255, 255, 255));
    replButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/circle-copy-24.png"))); // NOI18N
    replButton.setText("Replace");

    actionLabel7.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/circle-back-24.png"))); // NOI18N
    actionLabel7.setText("Undo");

    actionLabel8.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/circle-forward-24.png"))); // NOI18N
    actionLabel8.setText("Redo");

    actionLabel9.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/font-24.png"))); // NOI18N
    actionLabel9.setText("Font");

    actionLabel10.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/colors-24.png"))); // NOI18N
    actionLabel10.setText("Colors");

    javax.swing.GroupLayout buttonBarLayout = new javax.swing.GroupLayout(buttonBar);
    buttonBar.setLayout(buttonBarLayout);
    buttonBarLayout.setHorizontalGroup(
      buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(buttonBarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(buttonBarLayout.createSequentialGroup()
            .addComponent(actionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(actionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(buttonBarLayout.createSequentialGroup()
            .addComponent(actionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(actionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(actionLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(actionLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(actionLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(replButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(actionLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(actionLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    buttonBarLayout.setVerticalGroup(
      buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(buttonBarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(buttonBarLayout.createSequentialGroup()
            .addComponent(actionLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(actionLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(buttonBarLayout.createSequentialGroup()
            .addComponent(actionLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(actionLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(buttonBarLayout.createSequentialGroup()
            .addComponent(actionLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(replButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(buttonBarLayout.createSequentialGroup()
            .addGroup(buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(actionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(actionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(actionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(actionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    content.add(buttonBar, java.awt.BorderLayout.NORTH);
    content.add(scroll, java.awt.BorderLayout.CENTER);

    jMenu1.setText("File");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrameEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrameEditor().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private us.pserver.coder.ActionLabel actionLabel1;
  private us.pserver.coder.ActionLabel actionLabel10;
  private us.pserver.coder.ActionLabel actionLabel2;
  private us.pserver.coder.ActionLabel actionLabel3;
  private us.pserver.coder.ActionLabel actionLabel4;
  private us.pserver.coder.ActionLabel actionLabel5;
  private us.pserver.coder.ActionLabel actionLabel7;
  private us.pserver.coder.ActionLabel actionLabel8;
  private us.pserver.coder.ActionLabel actionLabel9;
  private javax.swing.JPanel buttonBar;
  private javax.swing.JPanel content;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private us.pserver.coder.ActionLabel replButton;
  private javax.swing.JScrollPane scroll;
  // End of variables declaration//GEN-END:variables
}
