/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package us.pserver.coder;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JComponent;


/**
 *
 * @author juno
 */
public class PanelConfig extends javax.swing.JPanel {

  private DefaultListModel<JComponent> model;
  
  private FrameEditor frame;
  
  
  /**
   * Creates new form PanelConfig
   */
  public PanelConfig() {
    initComponents();
    model = new DefaultListModel();
    
    ListSeparator sep = new ListSeparator();
    sep.label.setText("Text Area");
    model.addElement(sep);
    FormAttribute attr = new FormAttribute();
    attr.label.setText("Background Color:");
    attr.button.setOpaque(true);
    attr.button.setBackground(Color.red);
  }
  
  
  private FormAttribute createColorForm(String label, Color c) {
    FormAttribute attr = new FormAttribute();
    attr.label.setText(label);
    attr.button.setOpaque(true);
    attr.button.setBackground(c);
    attr.button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        attr.setValue(JColorChooser
            .showDialog(PanelConfig.this, "Choose "+ label, c));
        attr.button.setBackground(attr.castValue());
        attr.button.repaint();
      }
    });
    return attr;
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlButtons = new javax.swing.JPanel();
    btnApply = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();
    scroll = new javax.swing.JScrollPane();

    pnlButtons.setBackground(new java.awt.Color(255, 255, 255));

    btnApply.setText("Apply");
    btnApply.setPreferredSize(new java.awt.Dimension(90, 30));

    btnCancel.setText("Cancel");
    btnCancel.setPreferredSize(new java.awt.Dimension(90, 30));

    javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
    pnlButtons.setLayout(pnlButtonsLayout);
    pnlButtonsLayout.setHorizontalGroup(
      pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
        .addContainerGap(131, Short.MAX_VALUE)
        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    pnlButtonsLayout.setVerticalGroup(
      pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(15, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scroll)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnApply;
  private javax.swing.JButton btnCancel;
  private javax.swing.JPanel pnlButtons;
  private javax.swing.JScrollPane scroll;
  // End of variables declaration//GEN-END:variables
}
