/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package us.pserver.coder;

import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;


/**
 *
 * @author juno
 */
public class PanelConfig extends javax.swing.JPanel {

  private FrameEditor frame;
  
  private DefaultListModel<ConfigAttribute> model;
  
  
  /**
   * Creates new form PanelConfig
   */
  public PanelConfig(FrameEditor fe) {
    super();
    if(fe == null)
      throw new IllegalArgumentException(
          "Invalid FrameEditor (fe="+ fe+ ")");
    
    frame = fe;
    model = new DefaultListModel<>();
    
    model.addElement(new SeparatorAttribute("Text Area"));
    model.addElement(new FontAttribute("Text Font", frame.getConfig().getTextFont(), frame::setTextFont));
    model.addElement(new ColorAttribute("Text Color", frame.getConfig().getTextColor(), frame::setTextColor));
    model.addElement(new ColorAttribute("Selection Color", frame.getConfig().getTextSelectionColor(), frame::setTextSelectionColor));
    model.addElement(new ColorAttribute("Background Color", frame.getConfig().getTextBgColor(), frame::setTextBGColor));
    
    model.addElement(new SeparatorAttribute("Lines Number"));
    model.addElement(new ColorAttribute("Number Color", frame.getConfig().getLinesColor(), frame::setLinesColor));
    model.addElement(new ColorAttribute("Background Color", frame.getConfig().getLinesBgColor(), frame::setLinesBGColor));
    
    model.addElement(new SeparatorAttribute("Status Bar"));
    model.addElement(new FontAttribute("Status Font", frame.getConfig().getStatusFont(), frame::setStatusFont));
    model.addElement(new ColorAttribute("Status Color", frame.getConfig().getStatusColor(), frame::setStatusColor));
    model.addElement(new ColorAttribute("Warning Color", frame.getConfig().getStatusWarnColor(), frame::setStatusWarnColor));
    model.addElement(new ColorAttribute("Backgroung Color", frame.getConfig().getStatusBgColor(), frame::setStatusBGColor));
    
    initComponents();
  }
  
  
  private Window getParentWindow() {
    Container c = this;
    while(c != null) {
      if(c instanceof Window)
        return (Window) c;
      c = c.getParent();
    }
    return null;
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scroll = new javax.swing.JScrollPane();
    list = new javax.swing.JList();
    jPanel1 = new javax.swing.JPanel();
    applyAction = new us.pserver.coder.ActionLabel();
    cancelAction = new us.pserver.coder.ActionLabel();

    list.setCellRenderer(new FormAttributeRenderer(frame));
    list.setModel(model);
    list.setToolTipText("Double Click to Edit");
    list.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        listMouseClicked(evt);
      }
    });
    scroll.setViewportView(list);

    jPanel1.setBackground(new java.awt.Color(77, 77, 77));

    applyAction.setForeground(new java.awt.Color(255, 255, 255));
    applyAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/check-white-20.png"))); // NOI18N
    applyAction.setText("Apply");
    applyAction.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        applyActionMouseClicked(evt);
      }
    });

    cancelAction.setForeground(new java.awt.Color(255, 255, 255));
    cancelAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/cancel-white-20.png"))); // NOI18N
    cancelAction.setText("Cancel");
    cancelAction.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        cancelActionMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cancelAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(applyAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(15, 15, 15))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(applyAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cancelAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(15, 15, 15))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        .addGap(1, 1, 1)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
    if(evt.getButton() == MouseEvent.BUTTON1
        && evt.getClickCount() > 1) {
      int idx = list.locationToIndex(evt.getPoint());
      if(idx >= 0 && idx < list.getModel().getSize()) {
        ConfigAttribute attr = (ConfigAttribute) list.getModel().getElementAt(idx);
        if(attr instanceof FontAttribute) {
          FontSelector fe = new FontSelector(getParentWindow(), true, (Font) attr.get());
          fe.setVisible(true);
          Font f = fe.getSelectedFont();
          if(f != null)
            attr.set(f);
        }
        else if(attr instanceof ColorAttribute) {
          Color c = JColorChooser.showDialog(this, attr.name(), (Color) attr.get());
          if(c != null) {
            attr.set(c);
          }
        }
      }
      list.setModel(model);
      list.setSelectedIndex(idx);
    }
  }//GEN-LAST:event_listMouseClicked

  
  private void cancelActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelActionMouseClicked
    Window w = this.getParentWindow();
    if(w != null)
      w.setVisible(false);
  }//GEN-LAST:event_cancelActionMouseClicked

  
  private void applyActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyActionMouseClicked
    for(int i = 0; i < model.getSize(); i++) {
      model.elementAt(i).define();
    }
    this.getParentWindow().setVisible(false);
    frame.saveConfig();
  }//GEN-LAST:event_applyActionMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private us.pserver.coder.ActionLabel applyAction;
  private us.pserver.coder.ActionLabel cancelAction;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JList list;
  private javax.swing.JScrollPane scroll;
  // End of variables declaration//GEN-END:variables
}
