/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package us.pserver.coder;

import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JColorChooser;


/**
 *
 * @author juno
 */
public class PanelConfig extends javax.swing.JPanel {

  private FrameEditor frame;
  
  
  /**
   * Creates new form PanelConfig
   */
  public PanelConfig(FrameEditor fe) {
    super();
    if(fe == null)
      throw new IllegalArgumentException(
          "Invalid FrameEditor (fe="+ fe+ ")");
    frame = fe;
    initComponents();
    
    content.add(new ListSeparator("Text Area"));
    content.add(createColorForm("Text Color", 
        frame.getConfig().getTextColor()));
    content.add(createColorForm("Selection Color", 
        frame.getConfig().getTextSelectionColor()));
    content.add(createColorForm("Background Color", 
        frame.getConfig().getTextBgColor()));
    content.add(createFontForm("Text Font", 
        frame.getConfig().getTextFont()));
    
    content.add(new ListSeparator("Line Numbers"));
    content.add(createColorForm("Numbers Color", 
        frame.getConfig().getLinesColor()));
    content.add(createColorForm("Background Color", 
        frame.getConfig().getLinesBgColor()));
    
    content.add(new ListSeparator("Status Bar"));
    content.add(createColorForm("Status Color", 
        frame.getConfig().getStatusColor()));
    content.add(createColorForm("Warning Color", 
        frame.getConfig().getStatusWarnColor()));
    content.add(createColorForm("Background Color", 
        frame.getConfig().getStatusBgColor()));
    content.add(createFontForm("Status Font", 
        frame.getConfig().getStatusFont()));
  }
  
  
  private FormAttribute createColorForm(String label, Color c) {
    FormAttribute attr = new FormAttribute();
    attr.label.setText(label);
    attr.button.setOpaque(true);
    attr.button.setBackground(c);
    attr.button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        attr.setValue(JColorChooser
            .showDialog(PanelConfig.this, "Choose "+ label, c));
        attr.button.setBackground(attr.castValue());
        attr.button.repaint();
      }
    });
    return attr;
  }
  
  
  private FormAttribute createFontForm(String label, Font f) {
    FormAttribute attr = new FormAttribute();
    attr.label.setText(label);
    attr.button.setFont(f);
    attr.button.setText(f.getFamily());
    attr.button.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        FontSelector fs = new FontSelector(getParentFrame(), true, f);
        fs.setVisible(true);
        Font f = fs.getSelectedFont();
        if(f != null) {
          attr.setValue(f);
          attr.button.setFont(f);
          attr.button.setText(f.getFamily());
          attr.button.repaint();
        }
      }
    });
    return attr;
  }
  
  
  private Frame getParentFrame() {
    Container c = this;
    while(c != null) {
      if(c instanceof Frame)
        return (Frame) c;
      c = c.getParent();
    }
    return null;
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlButtons = new javax.swing.JPanel();
    actionLabel1 = new us.pserver.coder.ActionLabel();
    actionLabel2 = new us.pserver.coder.ActionLabel();
    scroll = new javax.swing.JScrollPane();
    content = new javax.swing.JPanel();

    pnlButtons.setBackground(new java.awt.Color(80, 80, 80));

    actionLabel1.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/check-white-24.png"))); // NOI18N
    actionLabel1.setText("Apply");

    actionLabel2.setForeground(new java.awt.Color(255, 255, 255));
    actionLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/cancel-white-24.png"))); // NOI18N
    actionLabel2.setText("Cancel");

    javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
    pnlButtons.setLayout(pnlButtonsLayout);
    pnlButtonsLayout.setHorizontalGroup(
      pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
        .addContainerGap(134, Short.MAX_VALUE)
        .addComponent(actionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(actionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    pnlButtonsLayout.setVerticalGroup(
      pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlButtonsLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(actionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(actionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(21, Short.MAX_VALUE))
    );

    content.setBackground(new java.awt.Color(255, 255, 255));
    content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.Y_AXIS));
    scroll.setViewportView(content);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(scroll, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        .addGap(3, 3, 3)
        .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private us.pserver.coder.ActionLabel actionLabel1;
  private us.pserver.coder.ActionLabel actionLabel2;
  private javax.swing.JPanel content;
  private javax.swing.JPanel pnlButtons;
  private javax.swing.JScrollPane scroll;
  // End of variables declaration//GEN-END:variables
}
