/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package us.pserver.up;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.SwingUtilities;

/**
 *
 * @author juno
 */
public class Upper extends javax.swing.JFrame {

  private TextCopy copy;
  
  /**
   * Creates new form Upper
   */
  public Upper() {
    initComponents();
    copy = new TextCopy();
    upperCheck.setSelected(true);
    autoCheck.setSelected(true);
    this.setLocationRelativeTo(null);
  }
  
  
  public void updateText() {
    String text = editArea.getText();
    boolean upper = upperCheck.isSelected();
    
    //(?<=(FROM|JOIN) ).+(WHERE|JOIN|;|$)
    //[a-zA-Z0-9_]+[\\.]{1}
    //(?<=AS[\s]).+\b
    text = (upper ? text.toUpperCase() : text.toLowerCase());
    Pattern pt = Pattern.compile("(?<=(FROM|JOIN)[\\s]).+(WHERE|JOIN|;|$|\n|\r)");
    Matcher mt = pt.matcher(text);
    while(mt.find()) {
      String sm = text.substring(mt.start(), mt.end());
      sm = (upper ? sm.toLowerCase() : sm.toUpperCase());
      text = text.substring(0, mt.start()) + sm + text.substring(mt.end());
    }
    pt = Pattern.compile("[a-zA-Z0-9_]+[\\.]{1}");
    mt = pt.matcher(text);
    while(mt.find()) {
      String sm = text.substring(mt.start(), mt.end());
      sm = (upper ? sm.toLowerCase() : sm.toUpperCase());
      text = text.substring(0, mt.start()) + sm + text.substring(mt.end());
    }
    pt = Pattern.compile("(?<=\\$)[a-zA-Z0-9_]+");
    mt = pt.matcher(text);
    while(mt.find()) {
      String sm = text.substring(mt.start(), mt.end());
      sm = (upper ? sm.toLowerCase() : sm.toUpperCase());
      text = text.substring(0, mt.start()) + sm + text.substring(mt.end());
    }
    
    upperArea.setText(text);
    if(text != null && !text.trim().isEmpty() 
        && autoCheck.isSelected())
      copy.setText(upperArea.getText()).putInClipboard();
    
    SwingUtilities.invokeLater(()->{
      upperArea.setSelectionStart(0);
      upperArea.setSelectionEnd(upperArea.getText().length());
      upperArea.select(0, upperArea.getText().length());
      upperArea.paint(upperArea.getGraphics());
    });
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    editArea = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    upperArea = new javax.swing.JTextArea();
    upperCheck = new javax.swing.JCheckBox();
    autoCheck = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Upper Case Tool");
    addWindowFocusListener(new java.awt.event.WindowFocusListener() {
      public void windowGainedFocus(java.awt.event.WindowEvent evt) {
        formWindowGainedFocus(evt);
      }
      public void windowLostFocus(java.awt.event.WindowEvent evt) {
      }
    });

    jSplitPane1.setDividerLocation(160);
    jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    editArea.setColumns(20);
    editArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
    editArea.setRows(5);
    editArea.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        editAreaKeyReleased(evt);
      }
    });
    jScrollPane1.setViewportView(editArea);

    jSplitPane1.setTopComponent(jScrollPane1);

    upperArea.setColumns(20);
    upperArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
    upperArea.setRows(5);
    jScrollPane2.setViewportView(upperArea);

    jSplitPane1.setRightComponent(jScrollPane2);

    upperCheck.setText("To UPPER Case");
    upperCheck.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        upperCheckActionPerformed(evt);
      }
    });

    autoCheck.setText("Auto Copy");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(110, Short.MAX_VALUE)
        .addComponent(upperCheck)
        .addGap(18, 18, 18)
        .addComponent(autoCheck)
        .addContainerGap(110, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(upperCheck)
          .addComponent(autoCheck)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  
  private void editAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editAreaKeyReleased
    updateText();
    
    if(evt.getKeyCode() != KeyEvent.VK_C
        || !evt.isControlDown())
      return;
    
    int selstart = editArea.getSelectionStart();
    int selend = editArea.getSelectionEnd();
    if(selstart == selend)
      copy.setText(upperArea.getText()).putInClipboard();
    else
      copy.setText(editArea.getSelectedText()).putInClipboard();
  }//GEN-LAST:event_editAreaKeyReleased

  
  private void upperCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperCheckActionPerformed
    updateText();
  }//GEN-LAST:event_upperCheckActionPerformed

  
  private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    editArea.requestFocus();
    editArea.requestFocusInWindow();
  }//GEN-LAST:event_formWindowGainedFocus

  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Upper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Upper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Upper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Upper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Upper().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox autoCheck;
  private javax.swing.JTextArea editArea;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTextArea upperArea;
  private javax.swing.JCheckBox upperCheck;
  // End of variables declaration//GEN-END:variables
}
