/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ButtonsGrid.java
 *
 * Created on 25/11/2010, 11:06:15
 */

package com.power.visual.test;

import com.power.visual.controls.PaintStyle;

/**
 *
 * @author f6036477
 */
public class ButtonsGrid extends javax.swing.JFrame {

    /** Creates new form ButtonsGrid */
    public ButtonsGrid() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    blackButton1 = new com.power.visual.controls.BlackButton(PaintStyle.RED_STYLE, "");
    blackButton2 = new com.power.visual.controls.BlackButton(PaintStyle.BLACK_STYLE, "");
    blackButton3 = new com.power.visual.controls.BlackButton(PaintStyle.BLUE_STYLE, "");
    blackButton4 = new com.power.visual.controls.BlackButton(PaintStyle.YELLOW_STYLE, "");
    blackButton5 = new com.power.visual.controls.BlackButton(PaintStyle.GREEN_STYLE, "");
    blackButton6 = new com.power.visual.controls.BlackButton(PaintStyle.WINXP_STYLE, "");
    blackButton7 = new com.power.visual.controls.BlackButton(PaintStyle.GRADIENT_BLACK, "");
    blackButton8 = new com.power.visual.controls.BlackButton(PaintStyle.GRADIENT_BLUE, "");
    blackButton9 = new com.power.visual.controls.BlackButton(PaintStyle.GRADIENT_YELLOW, "");
    blackButton10 = new com.power.visual.controls.BlackButton(PaintStyle.GRADIENT_GREEN, "");
    blackButton11 = new com.power.visual.controls.BlackButton(PaintStyle.GRADIENT_WINXP, "");
    blackButton12 = new com.power.visual.controls.BlackButton(PaintStyle.GRADIENT_RED, "");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    blackButton1.setText("Red Style");

    blackButton2.setText("Black Style");

    blackButton3.setText("Blue Style");

    blackButton4.setText("Yellow Style");

    blackButton5.setText("Green Style");

    blackButton6.setText("Winxp Style");

    blackButton7.setText("Gradient Black");

    blackButton8.setText("Gradient Blue");

    blackButton9.setText("Gradient Yellow");

    blackButton10.setText("Gradient Green");

    blackButton11.setText("Gradient Winxp");

    blackButton12.setText("Gradient Red");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(blackButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addComponent(blackButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(blackButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addComponent(blackButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(blackButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addComponent(blackButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(blackButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addComponent(blackButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(blackButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addComponent(blackButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(blackButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addComponent(blackButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(1, 1, 1)
            .addComponent(blackButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(blackButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(blackButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(blackButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(blackButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(blackButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(blackButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(blackButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(blackButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(blackButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(blackButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(blackButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ButtonsGrid().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.power.visual.controls.BlackButton blackButton1;
  private com.power.visual.controls.BlackButton blackButton10;
  private com.power.visual.controls.BlackButton blackButton11;
  private com.power.visual.controls.BlackButton blackButton12;
  private com.power.visual.controls.BlackButton blackButton2;
  private com.power.visual.controls.BlackButton blackButton3;
  private com.power.visual.controls.BlackButton blackButton4;
  private com.power.visual.controls.BlackButton blackButton5;
  private com.power.visual.controls.BlackButton blackButton6;
  private com.power.visual.controls.BlackButton blackButton7;
  private com.power.visual.controls.BlackButton blackButton8;
  private com.power.visual.controls.BlackButton blackButton9;
  // End of variables declaration//GEN-END:variables

}
