/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package us.pserver.tmo;

import java.awt.Container;
import java.awt.Frame;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import us.pserver.scron.Schedule;


/**
 *
 * @author Juno
 */
public class NewJobDialog extends javax.swing.JDialog {

  private Schedule sched;
  
  private String script;
  
  /**
   * Creates new form NewScheduleDialog
   */
  public NewJobDialog() {
    super((Frame) null, true);
    initComponents();
  }
  
  
  public ScriptPair getJobPair() {
    if(sched == null || script == null)
      return null;
    return new ScriptPair(sched, new ScriptJob(script)
        .setEnabled(enabledBox.isSelected()));
  }
  
  
  public void setJobPair(ScriptPair pair) {
    if(pair == null || pair.schedule() == null
        || pair.job() == null) return;
    sched = pair.schedule();
    script = pair.job().getScriptPath().toString();
    enabledBox.setSelected(pair.job().isEnabled());
    schedInput.setText(sched.toString());
    scriptInput.setText(script);
  }
  
  
  public ScriptPair showDialog(Container c) {
    this.setLocationRelativeTo(c);
    this.setVisible(true);
    return this.getJobPair();
  }
  
  
  public ScriptPair showDialog(ScriptPair p, Container c) {
    this.setJobPair(p);
    return this.showDialog(c);
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    schedInput = new javax.swing.JTextField();
    scriptButton = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    scriptInput = new javax.swing.JTextField();
    schedButton = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    enabledBox = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Job Configuration");
    setIconImage(new ImageIcon(getClass().getResource("/us/pserver/tmo/imgs/timer-blue-32.png")).getImage());

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel1.setText("Script File:");

    schedInput.setEditable(false);
    schedInput.setBackground(new java.awt.Color(239, 239, 239));
    schedInput.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

    scriptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/tmo/imgs/folder-blue-20.png"))); // NOI18N
    scriptButton.setToolTipText("Select Script File");
    scriptButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        scriptButtonActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel2.setText("Schedule:");

    scriptInput.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

    schedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/tmo/imgs/hourglass-icon-20.png"))); // NOI18N
    schedButton.setToolTipText("Create a Schedule");
    schedButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        schedButtonActionPerformed(evt);
      }
    });

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/tmo/imgs/cancel-20.png"))); // NOI18N
    cancelButton.setToolTipText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/tmo/imgs/ok-18.png"))); // NOI18N
    okButton.setToolTipText("Ok");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    enabledBox.setSelected(true);
    enabledBox.setText("Enabled");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(schedInput, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
          .addComponent(scriptInput))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(schedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(scriptButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(enabledBox)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(scriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(scriptInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(schedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2)
          .addComponent(schedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(enabledBox)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  
  private void schedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedButtonActionPerformed
    ScheduleDialog sd = new ScheduleDialog();
    sched = sd.setSchedule(sched)
        .showScheduleDialog(this);
    if(sched == null) return;
    schedInput.setText(sched.toString());
  }//GEN-LAST:event_schedButtonActionPerformed

  
  private void scriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptButtonActionPerformed
    JFileChooser ch = new JFileChooser(script);
    if(ch.showOpenDialog(this) != JFileChooser.APPROVE_OPTION)
      return;
    File f = ch.getSelectedFile();
    ch = null;
    if(f == null) return;
    script = f.toString();
    scriptInput.setText(script);
  }//GEN-LAST:event_scriptButtonActionPerformed

  
  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    sched = null;
    script = null;
    this.dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  
  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    if(sched == null || script == null) {
      scriptInput.requestFocus();
      return;
    }
    this.dispose();
  }//GEN-LAST:event_okButtonActionPerformed

  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(NewJobDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(NewJobDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(NewJobDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(NewJobDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    System.out.println("* "
        + new NewJobDialog().showDialog(null));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JCheckBox enabledBox;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton okButton;
  private javax.swing.JButton schedButton;
  private javax.swing.JTextField schedInput;
  private javax.swing.JButton scriptButton;
  private javax.swing.JTextField scriptInput;
  // End of variables declaration//GEN-END:variables
}
