/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package us.pserver.mapshare;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;


/**
 *
 * @author juno
 */
public class CredentialsDialog extends javax.swing.JDialog {
  
  public static final char BULLET_CHAR = '\u2022';

  private Credentials cred;
  
  
  /**
   * Creates new form CredentialsDialog
   */
  public CredentialsDialog(java.awt.Frame parent) {
    super(parent, true);
    cred = new Credentials();
    initComponents();
    this.setListeners();
    this.setLocationRelativeTo(null);
    this.setLookAndFeel();
    this.setSize(this.getWidth(), this.getHeight() -15);
    passField.setEchoChar(BULLET_CHAR);
  }
  
  
  private void setListeners() {
    KeyListener keyl = new KeyListener() {
      @Override public void keyTyped(KeyEvent e) {}
      @Override public void keyReleased(KeyEvent e) {}
      @Override
      public void keyPressed(KeyEvent e) {
        if(e.getComponent() == userField) {
          if(e.getKeyCode() == KeyEvent.VK_ENTER)
            passField.requestFocus();
          else if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
            cancelButtonActionPerformed(null);
        }
        else if(e.getComponent() == passField
            || e.getComponent() == okButton
            || e.getComponent() == rememberCheck) {
          if(e.getKeyCode() == KeyEvent.VK_ENTER)
            okButtonActionPerformed(null);
          else if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
            cancelButtonActionPerformed(null);
        }
        else if(e.getComponent() == cancelButton) {
          if(e.getKeyCode() == KeyEvent.VK_ENTER)
            cancelButtonActionPerformed(null);
        }
      }
    };
    userField.addKeyListener(keyl);
    passField.addKeyListener(keyl);
    okButton.addKeyListener(keyl);
    cancelButton.addKeyListener(keyl);
    rememberCheck.addKeyListener(keyl);
  }
  
  
  private void setLookAndFeel() {
    try {
      UIManager.setLookAndFeel(new NimbusLookAndFeel());
    } catch (UnsupportedLookAndFeelException ex) {}
    SwingUtilities.updateComponentTreeUI(this);
  }
  
  
  public Credentials showDialog() {
    this.setVisible(true);
    return cred;
  }
  
  
  public void setFirstLineText(String text) {
    firstLine.setText(text);
  }
  
  
  public void setSecondLineText(String text) {
    secondLine.setText(text);
  }
  
  
  public void setUserLabel(String label) {
    userLabel.setText(label);
  }
  
  
  public void setPasswordLabel(String label) {
    passLabel.setText(label);
  }
  
  
  public void setOkButtonLabel(String label) {
    okButton.setText(label);
  }
  
  
  public void setCancelButtonLabel(String label) {
    cancelButton.setText(label);
  }
  
  
  public String getFirstLineText() {
    return firstLine.getText();
  }
  
  
  public String getSecondLineText() {
    return secondLine.getText();
  }
  
  
  public String getUserLabel() {
    return userLabel.getText();
  }
  
  
  public String getPasswordLabel() {
    return passLabel.getText();
  }
  
  
  public String getOkButtonLabel() {
    return okButton.getText();
  }
  
  
  public String getCancelButtonLabel() {
    return cancelButton.getText();
  }
  
  
  public boolean isRememberChecked() {
    return rememberCheck.isSelected();
  }
  
  
  public JLabel firstLine() {
    return firstLine;
  }
  
  
  public JLabel secondLine() {
    return secondLine;
  }
  
  
  public JLabel userLabel() {
    return userLabel;
  }
  
  
  public JLabel passwordLabel() {
    return passLabel;
  }
  
  
  public JButton okButton() {
    return okButton;
  }
  
  
  public JButton cancelButton() {
    return cancelButton;
  }
  
  
  public Credentials getCredentials() {
    return cred;
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    firstLine = new javax.swing.JLabel();
    secondLine = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    userLabel = new javax.swing.JLabel();
    passLabel = new javax.swing.JLabel();
    userField = new javax.swing.JTextField();
    passField = new javax.swing.JPasswordField();
    jLabel5 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    rememberCheck = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Segurança de Rede");
    setAlwaysOnTop(true);
    setBackground(new java.awt.Color(239, 238, 239));
    setModal(true);
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    firstLine.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
    firstLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    firstLine.setText("O servidor da Rede MAN requer um nome de usuário e senha.");

    secondLine.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
    secondLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    secondLine.setText("Informe matrícula e senha da Rede MAN");

    userLabel.setForeground(new java.awt.Color(102, 102, 102));
    userLabel.setText("Usuário:");

    passLabel.setForeground(new java.awt.Color(102, 102, 102));
    passLabel.setText("Senha:");

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/mapshare/lock_64.png"))); // NOI18N

    jPanel2.setBackground(new java.awt.Color(239, 239, 239));

    cancelButton.setText("Cancelar");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cancelButton)
          .addComponent(okButton))
        .addContainerGap(15, Short.MAX_VALUE))
    );

    rememberCheck.setText("Lembrar minhas credenciais");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(firstLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(secondLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jSeparator1))
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel5)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(passLabel)
                  .addComponent(userLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(userField)
                  .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(rememberCheck)))
            .addGap(61, 61, 61))))
      .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(firstLine)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(secondLine)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(userLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(passLabel)
              .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rememberCheck)
        .addGap(18, 18, 18)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  
  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    if(userField.getText() != null)
      cred.setUser(userField.getText());
    char[] pass = passField.getPassword();
    if(pass != null && pass.length > 0)
      cred.setPasswd(pass);
    this.dispose();
  }//GEN-LAST:event_okButtonActionPerformed

  
  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    CredentialsDialog cd = new CredentialsDialog(null);
    Credentials c = cd.showDialog();
    if(c.getPasswd() != null)
      System.out.println("* Credentials{ user="+ c.getUser()+ ", pass="+ new String(c.getPasswd())+ " }");
    else
      System.out.println("* Credentials{ user="+ c.getUser()+ ", pass=<null> }");
    
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
  }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CredentialsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CredentialsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CredentialsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CredentialsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the dialog 
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        CredentialsDialog dialog = new CredentialsDialog(new javax.swing.JFrame());
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });*/
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel firstLine;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JButton okButton;
  private javax.swing.JPasswordField passField;
  private javax.swing.JLabel passLabel;
  private javax.swing.JCheckBox rememberCheck;
  private javax.swing.JLabel secondLine;
  private javax.swing.JTextField userField;
  private javax.swing.JLabel userLabel;
  // End of variables declaration//GEN-END:variables
}
