/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package us.pserver.redfs.ui;

import us.pserver.redfs.RemoteFile;
import us.pserver.redfs.RemoteFileSystem;
import us.pserver.rob.NetConnector;
import us.pserver.rob.RemoteException;


/**
 *
 * @author juno
 */
public class NewJFrame extends javax.swing.JFrame {

  private RemoteFile r;
  
  /**
   * Creates new form NewJFrame
   */
  public NewJFrame(RemoteFile rf) {
    r = rf;
    initComponents();
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    fileLabel1 = new us.pserver.redfs.ui.FileLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    fileLabel1.setText("fileLabel1");
    fileLabel1.setFile(r);
    fileLabel1.addMouseListener(fileLabel1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(fileLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(345, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(fileLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(275, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) throws RemoteException {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    RemoteFileSystem rs = new RemoteFileSystem(
        //new NetConnector("172.24.75.19", 11011)
        //new NetConnector("10.100.0.105", 11011)
        new NetConnector()
        .setAutoCloseConnetcion(false));
    //RemoteFile rf = rs.getFile("c:/users/juno/downloads/red-fs.jar");
    RemoteFile rf = rs.getFile("d:/ubuntu.zip");
    
    NewJFrame nf = new NewJFrame(rf);
    nf.setVisible(true);
    
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private us.pserver.redfs.ui.FileLabel fileLabel1;
  // End of variables declaration//GEN-END:variables
}
