/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package us.pserver.coder.ui;

import java.awt.event.KeyEvent;
import us.pserver.cdr.b64.Base64StringCoder;

/**
 *
 * @author juno
 */
public class Base64Converter extends javax.swing.JDialog {

  private Base64StringCoder cdr;
  
  private String str;
  
  
  /**
   * Creates new form Base64Converter
   */
  public Base64Converter(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    cdr = new Base64StringCoder();
    initComponents();
  }
  
  
  public String getConverted() {
    if(str == null) return null;
    return "\""+ cdr.encode(str)+ "\"";
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    content = new javax.swing.JPanel();
    pnlConvert = new javax.swing.JPanel();
    lblText = new javax.swing.JLabel();
    txtText = new javax.swing.JTextField();
    lblPassword = new javax.swing.JLabel();
    pwdPassword = new javax.swing.JPasswordField();
    btnText = new javax.swing.JButton();
    btnPassword = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    content.setBackground(new java.awt.Color(255, 255, 255));

    pnlConvert.setBackground(new java.awt.Color(255, 255, 255));
    pnlConvert.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Convert to Base64", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

    lblText.setText("Text:");

    txtText.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtTextKeyReleased(evt);
      }
    });

    lblPassword.setText("Password:");

    pwdPassword.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        pwdPasswordKeyReleased(evt);
      }
    });

    btnText.setText(">>");
    btnText.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTextActionPerformed(evt);
      }
    });

    btnPassword.setText(">>");
    btnPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPasswordActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlConvertLayout = new javax.swing.GroupLayout(pnlConvert);
    pnlConvert.setLayout(pnlConvertLayout);
    pnlConvertLayout.setHorizontalGroup(
      pnlConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlConvertLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtText)
          .addComponent(pwdPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(pnlConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnText)
          .addComponent(btnPassword))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlConvertLayout.setVerticalGroup(
      pnlConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlConvertLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblPassword)
          .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnPassword))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblText)
          .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnText))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
    content.setLayout(contentLayout);
    contentLayout.setHorizontalGroup(
      contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(contentLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(pnlConvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    contentLayout.setVerticalGroup(
      contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(contentLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(pnlConvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  
  private void btnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextActionPerformed
    str = txtText.getText();
    this.dispose();
  }//GEN-LAST:event_btnTextActionPerformed

  
  private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
    str = new String(pwdPassword.getPassword());
    this.dispose();
  }//GEN-LAST:event_btnPasswordActionPerformed

  private void pwdPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdPasswordKeyReleased
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      this.btnPasswordActionPerformed(null);
  }//GEN-LAST:event_pwdPasswordKeyReleased

  private void txtTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextKeyReleased
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      this.btnTextActionPerformed(null);
  }//GEN-LAST:event_txtTextKeyReleased

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Base64Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Base64Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Base64Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Base64Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        Base64Converter dialog = new Base64Converter(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnPassword;
  private javax.swing.JButton btnText;
  private javax.swing.JPanel content;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblText;
  private javax.swing.JPanel pnlConvert;
  private javax.swing.JPasswordField pwdPassword;
  private javax.swing.JTextField txtText;
  // End of variables declaration//GEN-END:variables
}
