/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package us.pserver.coder.ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.Window;
import javax.swing.JColorChooser;
import us.pserver.coder.FontXml;
import us.pserver.coder.Match;
import us.pserver.coder.TextStyle;

/**
 *
 * @author juno
 */
public class MatchConfigDialog extends javax.swing.JDialog {

  public static final String TITLE = "Style Configuration";
  
  private Color color;
  
  private Font font;
  
  
  /**
   * Creates new form MatchConfigDialog
   */
  public MatchConfigDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    this.setTitle(TITLE);
    initComponents();
  }
  
  
  public MatchConfigDialog(Window parent, boolean modal) {
    super(parent);
    this.setModal(modal);
    this.setTitle(TITLE);
    initComponents();
  }
  
  
  private boolean isEmpty(String str) {
    return str == null || str.trim().isEmpty();
  }
  
  
  public Match getMatch() {
    String name = txtName.getText();
    String regex = txtRegex.getText();
    if(isEmpty(name) 
        || isEmpty(regex) 
        || font == null 
        || color == null)
      return null;
    Match m = new Match(name, regex, new TextStyle());
    m.getTextStyle().setFontAttr(new FontXml().setFont(font));
    m.getTextStyle().setForeground(color);
    return m;
  }
  
  
  public void setMatch(Match m) {
    if(m == null) return;
    txtName.setText(m.getName());
    txtRegex.setText(m.getRegex());
    color = m.getTextStyle().getForeground();
    FontXml fx = m.getTextStyle().getFontAttr();
    if(fx != null) {
      font = fx.getFont();
      lblDemo.setFont(font);
    }
    lblDemo.setOpaque(true);
    lblDemo.setBackground(m.getTextStyle().getBackground());
    lblDemo.setForeground(color);
    lblDemo.setText(m.getName());
  }
  
  
  private void updateDemo() {
    lblDemo.setForeground(color);
    lblDemo.setFont(font);
    lblDemo.setText(txtName.getText());
    lblDemo.repaint();
  }
  
  
  public static Match showDialog(Window owner, Match orig) {
    MatchConfigDialog dlg = new MatchConfigDialog(owner, true);
    dlg.setMatch(orig);
    dlg.setLocationRelativeTo(owner);
    dlg.setVisible(true);
    return dlg.getMatch();
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblName = new javax.swing.JLabel();
    txtName = new javax.swing.JTextField();
    lblColor = new javax.swing.JLabel();
    lblFont = new javax.swing.JLabel();
    btnFont = new javax.swing.JButton();
    btnFG = new javax.swing.JButton();
    lblDemo = new javax.swing.JLabel();
    lblRegex = new javax.swing.JLabel();
    txtRegex = new javax.swing.JTextField();
    btnApply = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    lblName.setText("Name:");

    txtName.setToolTipText("Attribute Name");
    txtName.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        txtNameKeyPressed(evt);
      }
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtNameKeyReleased(evt);
      }
    });

    lblColor.setText("Color:");

    lblFont.setText("Font:");

    btnFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/font-gray-20.png"))); // NOI18N
    btnFont.setToolTipText("Font Selector");
    btnFont.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFontActionPerformed(evt);
      }
    });

    btnFG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/color-gray-20.png"))); // NOI18N
    btnFG.setToolTipText("Foreground Color");
    btnFG.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    btnFG.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFGActionPerformed(evt);
      }
    });

    lblDemo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblDemo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

    lblRegex.setText("Regex:");

    txtRegex.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
    txtRegex.setToolTipText("Regular Expression Matcher");

    btnApply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/ok-gray-16.png"))); // NOI18N
    btnApply.setText("Apply");
    btnApply.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnApplyActionPerformed(evt);
      }
    });

    btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/us/pserver/coder/images/cancel-gray-16.png"))); // NOI18N
    btnCancel.setText("Cancel");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(lblDemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(lblRegex)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtRegex, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnFG)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFont)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnFont)))))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnCancel)
            .addGap(18, 18, 18)
            .addComponent(btnApply)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblName)
          .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblRegex)
          .addComponent(txtRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnFont, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblFont, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnApply)
          .addComponent(btnCancel))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
    updateDemo();
  }//GEN-LAST:event_txtNameKeyPressed

  private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
    updateDemo();
  }//GEN-LAST:event_txtNameKeyReleased

  private void btnFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFontActionPerformed
    FontSelector fe = new FontSelector(this, true, font);
    fe.setVisible(true);
    font = fe.getSelectedFont();
    if(font != null) {
      this.updateDemo();
    }
  }//GEN-LAST:event_btnFontActionPerformed

  private void btnFGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFGActionPerformed
    color = JColorChooser.showDialog(this, "Foreground Color", color);
    this.updateDemo();
  }//GEN-LAST:event_btnFGActionPerformed

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    color = null;
    font = null;
    this.dispose();
  }//GEN-LAST:event_btnCancelActionPerformed

  private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnApplyActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MatchConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MatchConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MatchConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MatchConfigDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the dialog */
    System.out.println(showDialog(null, null));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnApply;
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnFG;
  private javax.swing.JButton btnFont;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblColor;
  private javax.swing.JLabel lblDemo;
  private javax.swing.JLabel lblFont;
  private javax.swing.JLabel lblName;
  private javax.swing.JLabel lblRegex;
  private javax.swing.JTextField txtName;
  private javax.swing.JTextField txtRegex;
  // End of variables declaration//GEN-END:variables
}
