/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package us.pserver.j3270;

import java.awt.Frame;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author juno
 */
public class UseTermsDialog extends javax.swing.JDialog {
  
  public static final String USE_TERMS_FILE = "/us/pserver/j3270/useterms/use_terms.txt";

  /**
   * Creates new form UseTermsDialog
   */
  public UseTermsDialog(java.awt.Frame parent) {
    super(parent, true);
    initComponents();
    readUseTerms();
  }
  
  
  private void readUseTerms() {
    try {
      InputStream in = this.getClass().getResourceAsStream(USE_TERMS_FILE);
      BufferedReader rd = new BufferedReader(new InputStreamReader(in, Charset.forName("ISO-8859-1")));
      String ln = null;
      while((ln = rd.readLine()) != null) {
        textArea.append(ln);
        textArea.append("\n");
      }
    } catch(Exception e) {
      textArea.append("### ERROR READING USE TERMS FILE ###\n");
      textArea.append("------------------------------------\n");
      textArea.append(e.toString());
      textArea.append("\n");
      StackTraceElement[] els = e.getStackTrace();
      for(StackTraceElement s : els) {
        textArea.append(" - "+ s.toString());
        textArea.append("\n");
      }
    }
    textArea.setCaretPosition(0);
  }
  
  
  public boolean isAgreed() {
    return agreeCheck.isSelected();
  }
  
  
  public static boolean showDialog(Frame parent) {
    UseTermsDialog dlg = new UseTermsDialog(parent);
    dlg.setLocationRelativeTo(null);
    dlg.setVisible(true);
    return dlg.isAgreed();
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    titleLabel = new javax.swing.JLabel();
    separator = new javax.swing.JSeparator();
    scrollPane = new javax.swing.JScrollPane();
    textArea = new javax.swing.JTextArea();
    agreeCheck = new javax.swing.JCheckBox();
    okButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Termos de Uso");

    titleLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
    titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleLabel.setText("J3270: Termos de Uso");

    textArea.setEditable(false);
    textArea.setColumns(20);
    textArea.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
    textArea.setRows(5);
    scrollPane.setViewportView(textArea);

    agreeCheck.setText("Li e concordo com os Termos de Uso deste software.");

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(separator)
          .addGroup(layout.createSequentialGroup()
            .addComponent(agreeCheck)
            .addGap(0, 248, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(titleLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(agreeCheck)
        .addGap(19, 19, 19)
        .addComponent(okButton)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    if(!agreeCheck.isSelected()) {
      JOptionPane.showMessageDialog(this, 
          "Este software não poderá ser utilizado "
              + "sem a concordância dos termos de uso.", 
          "Alerta", JOptionPane.WARNING_MESSAGE);
    }
    this.dispose();
  }//GEN-LAST:event_okButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(UseTermsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(UseTermsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(UseTermsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(UseTermsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        System.out.println("* Agreed: "+ UseTermsDialog.showDialog(new JFrame()));
        System.exit(0);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox agreeCheck;
  private javax.swing.JButton okButton;
  private javax.swing.JScrollPane scrollPane;
  private javax.swing.JSeparator separator;
  private javax.swing.JTextArea textArea;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables
}
